Mobile portfolio
RHK-MICROVERSE/My-Portfolio pull request #1
Opened 2023-02-16 21:00 UTC by RHK-MICROVERSE

### In this pull request

- [ ] We implemented mobile sections of my portfolio
- [ ] Added readme
- [ ] No linters errors

2023-02-16 21:25 UTC, vickymarz requested changes
Hi @RHK-MICROVERSE, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

**I CAN SEE THAT MOST OF THE CHANGES WERE NOT IMPLEMENTED IN THIS PULL REQUEST WHICH IS MAKING IT DIFFICULT TO GIVE QUALITY REVIEWS. KINDLY ENSURE THAT ALL YOUR CHANGES ARE REFLECTED IN THE PULL REQUEST YOU ARE SUBMITTING.**

- [x] KIndly ensure you wrap your entire toolbar (logo and hamburger) in a header tag that is semantic enabling screen readers and search engines to understand what each content does 👍🏽. Get more info [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)

- [x] Kindly ensure that only your hamburger is wrapped in a nav tag as it will contain your navigation elements eventually. Your logo should be part of the header tag and not the nav tag

- [ ] Kindly ensure that the content of your toolbar is properly aligned together. Right now they are not properly aligned. Add `align-items: center` to properly align the contents to the center 

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219489027-9d8cff3e-7c7f-42ee-b48b-bc25a4075ff5.png)

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219489103-abcf385c-0502-4259-bbe8-ab28939dfc5e.png)

- [ ] Kindly ensure you use the right background color in your headline section. Currently, your background color is black but the figma design is #1C1A19. KIndly check it out.

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219489356-95d01538-eccb-4671-ba0a-d6459423f14a.png)

figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/219489467-fc4aa8ef-31e6-48cc-84cc-b82db2f83376.png)

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

- [ ] Kindly ensure that your list of icons are wrapped in a `<ul>` tag and `<li>`  tag per icon; and each icon has a link (a tag).

e.g 

 ```
   <ul>
         <li> 
              <a> icon </a> 
         </li>
     </ul>
```

- [ ] Kindly ensure that your main title (e.g., "I'm Marianne ...") is an `h1` tag. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info,

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 03:42 UTC, mahbubul14 requested changes
Hi @RHK-MICROVERSE,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [x] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-17 03:42 UTC, mahbubul14 commented on index.html
> +      <div> <img src="./images/m-icon.png" class="icon gmail"></a></div>
- [ ] As the previous reviewer suggested, Kindly ensure that your list of icons is wrapped in a `<ul>` tag and `<li>` tag per icon; and that each icon has a link (a tag).

e.g:

```
<ul>
        <li>
            <a> icon </a>
        </li>
</ul>
```

2023-02-17 03:42 UTC, mahbubul14 commented on index.html
>        <h3 class="activity">I am a Full Stack Developer</h2>
- [ ] Kindly give a proper space between the two sections and match it with the Figma design. Here is your design looks now:

![readme](https://user-images.githubusercontent.com/70483835/219543561-34d95923-5d4f-4928-aaa0-1c9e78dd6640.png)

2023-02-17 06:55 UTC, AdnanOlarmmi approved these changes
Hi @RHK-MICROVERSE,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice design.
- Professional README.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 06:55 UTC, AdnanOlarmmi commented on index.html
> +      <h1 class="greetings">Hey there. I'm Rassel</h1>
- [ ] [OPTIONAL] Kindly reduce the space a bit to make it more pixel-perfect, as you shall be doing in your soon coming life-changing future job 😀.

2023-02-17 07:01 UTC, merged